### ISSUE TITLE
Webコンテナーの環境変数について

### ISSUE THREAD

**Issue by tsubakimoto** [alterbooth/hol-microservices-app-development#3]
nodejsで作っているアプリは80番ポートを使えないため `step1-create-app.yaml` でポートフォワードする必要があります。そのためのyamlの内容が以下になります。

# step1-create-app.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-app-1-0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aks-app
      version: v1
  template:
    metadata:
      labels:
        app: aks-app
        version: v1
    spec:
      containers:
      - name: aks-app-web
        image: {ACRname}.azurecr.io/web:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
      - name: aks-app-api
        image: {ACRname}.azurecr.io/api:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: aks-app
  labels: 
    app: aks-app
spec:
  ports:
  - port: 80
    targetPort: 3000
    name: http
  selector:
    app: aks-app
  type: ClusterIP
```

---

WebコンテナーからAPIコンテナーにアクセスするには、Webコンテナーの環境変数 `API_ENDPOINT` に `http://{APIコンテナーのエンドポイント}:3001/api/message` を設定すればアプリケーションが動作します。

configmap に環境変数 `API_ENDPOINT` を設定してもらえますか？
